[package]
name = "slicer"
version = "0.1.0"
authors = ["Hugo Sabourin <hsabouri@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stl_io = "0.4.2"